# Generated by Django 2.2.7 on 2019-11-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('grade', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=180)),
                ('materials', models.CharField(max_length=300)),
                ('vocab', models.TextField()),
                ('description', models.TextField()),
                ('activities', models.TextField()),
                ('accommodations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('anchor_number', models.IntegerField()),
                ('anchor_text', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='crafting_core_lessons.Lesson')),
            ],
        ),
    ]
