# Generated by Django 2.2.7 on 2019-11-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting_core_lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standards',
            new_name='Standard',
        ),
    ]
