# Generated by Django 2.2.7 on 2019-11-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting_core_lessons', '0003_standard_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='anchor_number',
            new_name='anchor_standard_number',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='anchor_text',
            new_name='anchor_standard_text',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='text',
            new_name='standard_text',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='title',
            new_name='standard_title',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='lesson',
        ),
    ]
