# Generated by Django 2.2.7 on 2019-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting_core_lessons', '0004_auto_20191112_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='standard_title',
            field=models.ManyToManyField(related_name='lessons', to='crafting_core_lessons.Standard'),
        ),
    ]
